version: '3.8'
services:
  app:
    build: .
    environment:
      OLLAMA_HOST: host.docker.internal
      OLLAMA_PORT: 11434
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
